col status format a10

SELECT SEGMENT_NAME, STATUS, SUM(BYTES), COUNT(*)
FROM   DBA_UNDO_EXTENTS 
WHERE  SEGMENT_NAME like '%&segment_name%'
GROUP BY SEGMENT_NAME, STATUS
ORDER BY SEGMENT_NAME, STATUS
/
